#!/usr/bin/env node
/**
 * Vercel ビルド時に環境変数から config.js を生成する。
 *   vercel.json の buildCommand から呼ばれる。
 *
 * 使う環境変数（Vercel > Settings > Environment Variables）:
 *   SUPABASE_URL        … https://xxxx.supabase.co
 *   SUPABASE_ANON_KEY   … anon(public) キー
 *   BACKEND_MODE        … 'supabase' | 'gas'（省略時 supabase / URL未設定なら gas）
 *
 * 未設定でもビルドは失敗しない（空 config を出力 → UI設定にフォールバック）。
 */
import { writeFileSync } from 'node:fs';

const url = process.env.SUPABASE_URL || '';
const anon = process.env.SUPABASE_ANON_KEY || '';
const mode = process.env.BACKEND_MODE || (url && anon ? 'supabase' : 'gas');

const cfg = { backendMode: mode };
if (url) cfg.supabaseUrl = url;
if (anon) cfg.supabaseAnonKey = anon;

const body = `/* AUTO-GENERATED by scripts/gen-config.mjs — do not edit. */\nwindow.__VIE_CONFIG__ = ${JSON.stringify(cfg, null, 2)};\n`;
writeFileSync(new URL('../config.js', import.meta.url), body);
console.log(`config.js generated (mode=${mode}, supabase=${url ? 'set' : 'unset'})`);
